<?php



/**
 * @implements hook_menu();
 */
function d_tweaks_menu(){
	$items = array();
	//our autocomplete callback menu item
	$items['ajax/decypher'] = array(
		'page callback' => '_d_tweaks_decypher_code',
		'page arguments' => array(),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}




//function for extracting code while typing in the basic page node form
function _d_tweaks_decypher_code($code = ''){
	$code = !empty($_POST['code']) ? rawurldecode($_POST['code']) : NULL;
	$decypherd_text = '';
	if(isset($code)){
		$code = str_replace("<br />", "\n", $code);
		$code_prefix = str_replace('{code}', '<pre class="brush:php">', $code);
		$code_suffix = str_replace('{/code}', '</pre>', $code_prefix);
		$decypherd_text = $code_suffix;
	}
	drupal_json_output($decypherd_text);
}



function d_tweaks_form_alter(&$form, &$form_state, $form_id){
	switch($form_id){
		case 'page_node_form':
			drupal_add_js(drupal_get_path('module', 'd_tweaks') . '/js/drupal7_node_preview.js', array());
			drupal_add_css(drupal_get_path('module', 'd_tweaks') . '/css/d_tweaks.css', array());
			drupal_add_js(drupal_get_path('module', 'syntaxhighlighter') . '/syntaxhighlighter.min.js', array());
			$form['field_text_and_code']['und'][0]['#format'] = 'syntax_highlighter';
			$form['field_text_and_code']['und'][0]['#title'] = $form['field_text_and_code']['und'][0]['#title'] . '<a href="#" id="insert-code-button">{  }</a>';
			$form['title']['#weight'] = 1;
			$form['field_tags']['#weight'] = 3;
			$form['preview'] = array(
				'#type' => 'markup',
				'#markup' => '',
				'#prefix' => '<div id="node-preview-syntax" title="Preview">',
				'#suffix' => '</div>',
				'#weight' => 4,
			);
			//custom submit handler
			$form['#submit'][] = '_d_tweaks_page_form_submit';
			
		break;
	}
}




/**
 * @ function for making the node published or unpublished depending on what the user selects for field_page_type
 *
 */
function _d_tweaks_page_form_submit(&$form, &$form_state){
	switch($form_state['values']['field_page_type']['und'][0]['value']){
		case 'public':
			$form_state['values']['status'] = 1;
		break;
		case 'private':
			$form_state['values']['status'] = 0;
		break;
	}
	//convert our {code} place holde to <pre class="brush:php">
	if(!empty($form_state['values']['field_text_and_code']['und'][0]['value'])){
		$code = $form_state['values']['field_text_and_code']['und'][0]['value'];
		$code_prefix = str_replace('{code}', '<pre class="brush:php">', $code);
		$code_suffix = str_replace('{/code}', '</pre>', $code_prefix);
		$form_state['values']['field_text_and_code']['und'][0]['value'] = $code_suffix;
	}
}



/**
 * @ implements hook_page_alter();
 */
function d_tweaks_page_alter(&$page){

}